apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l5673quca-dotnet-basic
  janus-idp.io/tekton: l5673quca-dotnet-basic
  backstage.io/kubernetes-id: l5673quca-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l5673quca-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
